image: java:8
stages:
  - test
  - verify
  - deploy
build:
  stage: build
  script: ./mvnw clean install
  artifacts:
    paths:
      - target/site/jacoco/jacoco.csv
test:
  stage: test
  script: ./mvnw test
  artifacts:
    paths:
      - target/site/jacoco/jacoco.csv
verify:
  stage: verify
  script:
    - cat /etc/os-release
    - cat site/jacoco/jacoco.csv
production:
  stage: deploy
  script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push