spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/online_exam_system
    username: root
    password: 123456
  web:
    resources:
      static-locations: file:///${upload.path}
upload:
  path: /home/luongtx/workspace/personal/uploads/
  default-profile-image: avatar.png
  default-cert-image: cert-1.jpg
jwt:
  secret: luongtx
