spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:172.18.0.3}:3306/online_exam_system
    username: root
    password: 123456
  web:
    resources:
      static-locations: file:///${upload.path}
upload:
  path: uploads/
  default-profile-image: avatar.png
  default-cert-image: cert-1.jpg
jwt:
  secret: luongtx
server:
  port: 8081
